### ISSUE TITLE
Can not disable scroll on tableview

### ISSUE THREAD

**Issue by shuto-S** [Azuritul/AZDropdownMenu#10]
Maybe, set in initOverlay() is not enough.

> Example: `overlay. scrollEnabled  = false`

**Comment by Azuritul** [comment]
I am afraid I don't understand your question.  
Would you describe more about it?  Did you encounter a bug or did you try to achieve some effect without success?

**Comment by shuto-S** [comment]
I am sorry. My explanation was not enough.

I tried to use the AZDropdownMenu.
It was a success, However, under UIView can be scroll.

Is this specification?
While the AZDropdownMenu is being displayed is not want to scroll.

sample gif
https://gyazo.com/196c8cc6883fa9c55010899b025f8599

**Comment by Azuritul** [comment]
Ah, I see. Thanks for the sample picture. 
And no, that is not the intended behavior.  
I'll find some time to look into this problem.  

I would like to know what is the underlying view controller class for the screen(ランキング). 
An `UITableViewController` or an `UIViewController` with a tableview?

Thank you for reporting!

**Comment by shuto-S** [comment]
It is `UITableViewController`.

I appreciate that you dealt with my case quickly.

**Comment by han76816** [comment]
I try to use UIViewController with tableview also have this problem..

**Comment by Azuritul** [comment]
For now, to address this issue, I would recommend using a UIViewController with tableview instead of UITableViewController.  If you can't really change implementation, #15 should address part of the scrolling issue.  However there might be a need to do some more tuning on the calling view controller.

**Comment by han76816** [comment]
Hi, I was wondering whether menu should scroll or not because my items is too much to show on the screen lol

**Comment by Azuritul** [comment]
It depends, but in this occasion I think it might indicate that the dropdown is not the most suitable component to be used here.
