### ISSUE TITLE
Pod Installing Issue

### ISSUE THREAD

**Issue by SketchySwift** [Azuritul/AZDropdownMenu#13]
I am getting an error when I am installing the pod :( 
<img width="1347" alt="screen shot 2016-03-01 at 10 21 14 am" src="https://cloud.githubusercontent.com/assets/15222571/13431442/6b7d5f9a-df97-11e5-900d-59a635ea4fd0.png">

**Comment by Azuritul** [comment]
Seems to be related to Cocoapod configuration and had nothing to do with the library.  Google should be able to help here.
Good luck!
