### ISSUE TITLE
Can't see the first and second cell

### ISSUE THREAD

**Issue by YHSX88** [Azuritul/AZDropdownMenu#19]
Hi Guys 

I have this issue where I'm not able to see 1st and 2nd cell after I open the dropdown menu.

I used two heights first menu?.itemHeight = 40
![screen shot 2016-04-18 at 23 56 25](https://cloud.githubusercontent.com/assets/16823745/14619737/9b358e2e-05c1-11e6-9348-7c05626f79df.png)

and here i have menu?.itemHeight = 120
![screen shot 2016-04-19 at 00 00 44](https://cloud.githubusercontent.com/assets/16823745/14619765/c9c1a0a2-05c1-11e6-8c32-072cf45f7d47.png)

I'm not sure why but is not working. The nav bar is 44 in height

Can you help me with this ?

Thanks in Advance !

**Comment by Azuritul** [comment]
Can you set navigationBar's translucent property to false?

**Comment by YHSX88** [comment]
Yes that is fixing the problem I had, now I can see the first row with itemHeight of 10 even

Thanks Very Much !!!
