### ISSUE TITLE
Scroll when so many item menu.

### ISSUE THREAD

**Issue by quocvietktc** [Azuritul/AZDropdownMenu#20]
I have 30 menu item. But can't scroll. So have some menu item don't show in view. Can you make it scroll? Plz

**Comment by michalbielawski** [comment]
Quick fix: In AZDropdownMenu class in initMenu() func don't add UIPanGestureRecognizer to menuView

**Comment by quocvietktc** [comment]
Thank you. But need del menuView.scrollEnabled = false. I got it.
