### ISSUE TITLE
Any chance to upgrade to Swift 3 soon?

### ISSUE THREAD

**Issue by rmvz3** [Azuritul/AZDropdownMenu#27]
Hi. I love your library. You know we're all in XCode 8 updating nightmare. I wonder if you are planning to release a new swift 3 compatible version soon.

Thanks

**Comment by Azuritul** [comment]
Yes the library would be upgraded to Swift 3 by the end of October hopefully.

**Comment by rmvz3** [comment]
Great. That will be awesome. Thank you for answering.
